import json

country_flags = {
    "AND": "ad",
    "UAE": "ae",
    "ALB": "al",
    "ARM": "am",
    "ANG": "ao",
    "ARG": "ar",
    "AUT": "at",
    "AUS": "au",
    "AZE": "az",
    "BIH": "ba",
    "BAR": "bb",
    "BAN": "bd",
    "BEL": "be",
    "BUR": "bf",
    "BUL": "bg",
    "BRN": "bh",
    "BDI": "bi",
    "BEN": "bj",
    "BER": "bm",
    "BRU": "bn",
    "BOL": "bo",
    "BRA": "br",
    "BAH": "bs",
    "BHU": "bt",
    "BOT": "bw",
    "BLR": "by",
    "BIZ": "bz",
    "CAN": "ca",
    "COD": "cd",
    "CAF": "cf",
    "CGO": "cg",
    "SUI": "ch",
    "CIV": "ci",
    "CHI": "cl",
    "CMR": "cm",
    "CHN": "cn",
    "COL": "co",
    "CRC": "cr",
    "CUB": "cu",
    "CPV": "cv",
    "CYP": "cy",
    "CZE": "cz",
    "GER": "de",
    "DJI": "dj",
    "DEN": "dk",
    "DMA": "dm",
    "DOM": "do",
    "ALG": "dz",
    "ECU": "ec",
    "EST": "ee",
    "EGY": "eg",
    "ERI": "er",
    "ESP": "es",
    "ETH": "et",
    "FIN": "fi",
    "FIJ": "fj",
    "FSM": "fm",
    "FRO": "fo",
    "FRA": "fr",
    "GAB": "ga",
    "GBR": "gb",
    "GRN": "gd",
    "GEO": "ge",
    "GHA": "gh",
    "GRL": "gl",
    "GAM": "gm",
    "GUI": "gn",
    "GEQ": "gq",
    "GRE": "gr",
    "GUA": "gt",
    "GBS": "gw",
    "GUY": "gy",
    "HKG": "hk",
    "HON": "hn",
    "CRO": "hr",
    "HAI": "ht",
    "HUN": "hu",
    "INA": "id",
    "IRL": "ie",
    "ISR": "il",
    "IND": "in",
    "IRQ": "iq",
    "IRI": "ir",
    "ISL": "is",
    "ITA": "it",
    "JAM": "jm",
    "JOR": "jo",
    "JPN": "jp",
    "KEN": "ke",
    "KGZ": "kg",
    "CAM": "kh",
    "COM": "km",
    "SKN": "kn",
    "PRK": "kp",
    "KOR": "kr",
    "KUW": "kw",
    "KAZ": "kz",
    "LAO": "la",
    "LBN": "lb",
    "LCA": "lc",
    "LIE": "li",
    "SRI": "lk",
    "LBR": "lr",
    "LES": "ls",
    "LTU": "lt",
    "LUX": "lu",
    "LAT": "lv",
    "LBA": "ly",
    "MAR": "ma",
    "MNC": "mc",
    "MDA": "md",
    "MNE": "me",
    "MAD": "mg",
    "MKD": "mk",
    "MLI": "ml",
    "MYA": "mm",
    "MGL": "mn",
    "MTN": "mr",
    "MLT": "mt",
    "MRI": "mu",
    "MDV": "mv",
    "MAW": "mw",
    "MEX": "mx",
    "MAS": "my",
    "MOZ": "mz",
    "NAM": "na",
    "NIG": "ne",
    "NGR": "ng",
    "NCA": "ni",
    "NED": "nl",
    "NOR": "no",
    "NEP": "np",
    "NRU": "nr",
    "NZL": "nz",
    "OMA": "om",
    "PAN": "pa",
    "PER": "pe",
    "PNG": "pg",
    "PHI": "ph",
    "PAK": "pk",
    "POL": "pl",
    "PUR": "pr",
    "PLE": "ps",
    "POR": "pt",
    "PLW": "pw",
    "PAR": "py",
    "QAT": "qa",
    "ROU": "ro",
    "SRB": "rs",
    "RUS": "ru",
    "RWA": "rw",
    "KSA": "sa",
    "SOL": "sb",
    "SEY": "sc",
    "SUD": "sd",
    "SWE": "se",
    "SGP": "sg",
    "SLO": "si",
    "SVK": "sk",
    "SLE": "sl",
    "SMR": "sm",
    "SEN": "sn",
    "SOM": "so",
    "SUR": "sr",
    "SSD": "ss",
    "STP": "st",
    "ESA": "sv",
    "SYR": "sy",
    "SWZ": "sz",
    "CHA": "td",
    "TOG": "tg",
    "THA": "th",
    "TJK": "tj",
    "TLS": "tl",
    "TKM": "tm",
    "TUN": "tn",
    "TGA": "to",
    "TUR": "tr",
    "TTO": "tt",
    "TUV": "tv",
    "TPE": "tw",
    "TAN": "tz",
    "UKR": "ua",
    "UGA": "ug",
    "USA": "us",
    "URU": "uy",
    "UZB": "uz",
    "VIN": "vc",
    "VEN": "ve",
    "VIE": "vn",
    "VAN": "vu",
    "SAM": "ws",
    "KOS": "xk",
    "YEM": "ye",
    "RSA": "za",
    "ZAM": "zm",
    "ZIM": "zw",
}


def jsonround_to_player_json(ROUND_NUMBER):

    # Input data
    with open(f"rapid_open_round_{ROUND_NUMBER}.json", "r") as file:
        games = json.load(file)

    # Function to get player score
    def get_score(result, is_player1):
        result = result.replace(" ", "").replace("½", "1/2")
        if result == "1-0":
            return 1 if is_player1 else 0
        elif result == "0-1":
            return 0 if is_player1 else 1
        elif result == "1/2-1/2":
            return 0.5
        return 0

    # Transform data
    players = []
    for game in games:
        for player_key, is_player1 in [("Player1", True), ("Player2", False)]:
            player = game[player_key]
            country_code = country_flags.get(
                player["Country"], "un"
            )  # Default to "un" for unknown

            icon = f"https://flagsapi.com/{country_code.upper()}/flat/64.png"
            if country_code == "un":
                icon = "https://results.fide.com/wrbc2024/images/flags/FID.png"
            players.append(
                {
                    "date": f"1900-01-{ROUND_NUMBER:02}",
                    "name": f"{player['Name'].split(', ')[1]} {player['Name'].split(', ')[0]}",
                    "value": get_score(game["Result"], is_player1),
                    "icon": icon,
                    "group": player.get("Title", "None"),
                }
            )

    # Output JSON
    output_json = json.dumps(players, indent=2)
    print(output_json)

    # Write output to JSON file
    output_filename = f"rapid_open_round_{ROUND_NUMBER}_players.json"
    with open(output_filename, "w") as outfile:
        json.dump(players, outfile, indent=2)
